workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'      # Execute jobs when a new commit is pushed to master branch

stages:
    - checks
    - deploy

lint:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - pre-commit install
    - pre-commit run --all-files

configure script tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - python3 -m pip install pytest
    - python3 -m pytest -vv test/test_configure.py

integration tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cat /proc/cpuinfo
    - gcc --version

    - cd test
    - ./checks.sh
    - ./checks_mpi.sh

pages:
  image: python:3.7-alpine
  stage: deploy
  script:
  - pip install -U sphinx sphinx-rtd-theme
  - sphinx-build -b html doc/source public
  artifacts:
    paths:
    - public
  only:
  - master
