image: ubuntu:latest

variables:
    OMPI_ALLOW_RUN_AS_ROOT: '1'
    OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: '1'
    OMPI_MCA_btl_vader_single_copy_mechanism: 'none' # https://github.com/open-mpi/ompi/issues/4948

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq
  - apt-get install -qq build-essential openmpi-bin python3 python3-pip bc
  - export IDEFIX_DIR=$(pwd)/idefix

test:
  stage: test
  script:
    - cat /proc/cpuinfo
    - gcc --version
    - cd test/HD
    - ./checks.sh
  only:
  - branches
  #except:
  #- master

pages:
  stage: deploy
  script:
  - pip install -U sphinx sphinx-rtd-theme
  - sphinx-build -b html doc/source public
  artifacts:
    paths:
    - public
  only:
  - master

