variables:
  GIT_SUBMODULE_STRATEGY: recursive

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master' || $CI_COMMIT_BRANCH == 'develop'    # Execute jobs when a new commit is pushed to master or develop branch

stages:
    - checks
    - deploy

lint:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - pre-commit install
    - pre-commit run --all-files

HD tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cat /proc/cpuinfo
    - gcc --version

    - cd test
    - ./checks_hydro.sh

MHD tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cat /proc/cpuinfo
    - gcc --version

    - cd test
    - ./checks_mhd.sh

MPI tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cat /proc/cpuinfo
    - gcc --version

    - cd test
    - ./checks_mpi.sh

HighOrder tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cat /proc/cpuinfo
    - gcc --version

    - cd test
    - ./checks_highorder.sh

Examples tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cat /proc/cpuinfo
    - gcc --version

    - cd test
    - ./checks_examples.sh

pages:
  image: lesurg/idefix-documentation:latest
  stage: deploy
  script:
    - dir="public"
    - rm -rf $dir
    - sphinx-build -b html doc/source $dir
  artifacts:
    paths:
      - public
  only:
  - master
