image: python:3.7-alpine

test:
  stage: test
  script:
    - cat /proc/cpuinfo
    - gcc --version
    - cd test/HD
    - ./checks.sh
  only:
  - branches
  #except:
  #- master

pages:
  stage: deploy
  script:
  - pip install -U sphinx sphinx-rtd-theme
  - sphinx-build -b html doc/source public
  artifacts:
    paths:
    - public
  only:
  - master

