workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master' || $CI_COMMIT_BRANCH == 'develop'    # Execute jobs when a new commit is pushed to master or develop branch

stages:
    - checks
    - deploy

lint:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - pre-commit install
    - pre-commit run --all-files

configure script tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - python3 -m pip install pytest
    - python3 -m pytest -vv test/test_configure.py

HD tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cat /proc/cpuinfo
    - gcc --version

    - cd test
    - ./checks_hydro.sh

MHD tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cat /proc/cpuinfo
    - gcc --version

    - cd test
    - ./checks_mhd.sh

MPI tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cat /proc/cpuinfo
    - gcc --version

    - cd test
    - ./checks_mpi.sh

cache:
  # Required to keep artifacts from old builds, e.g. from master
  paths:
    - public

pages:
  image: lesurg/idefix-documentation:latest
  stage: deploy
  script:
    - dir="$CI_COMMIT_REF_SLUG"
    - dir="public/$dir"
    - rm -rf $dir
    - sphinx-build -b html doc/source $dir
  artifacts:
    paths:
      - public
  only:
  - master
  - develop
