variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .python-env/

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'    # Execute jobs when a new commit is pushed to master branch
    - if: $CI_PIPELINE_SOURCE == 'web'     # execute jobs when created by using Run pipeline button in the GitLab UI, from the project’s CI/CD > Pipelines section.

stages:
    - setup
    - checks
    - deploy


Setup python test env:
  stage: setup
  image: lesurg/idefix:latest
  script:
    - python3 --version
    - python3 -m venv .python-env
    - source .python-env/bin/activate
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r test/python_requirements.txt

lint:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - pre-commit install
    - pre-commit run --all-files

HD tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cd test
    - ./checks_hydro.sh $TEST_OPTIONS

MHD tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cd test
    - ./checks_mhd.sh $TEST_OPTIONS

Vector potential tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cd test
    - ./checks_vector_potential.sh $TEST_OPTIONS

MPI tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cd test
    - ./checks_mpi.sh $TEST_OPTIONS

HighOrder tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cd test
    - ./checks_highorder.sh $TEST_OPTIONS

SinglePrecision tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cd test
    - ./checks_singleprecision.sh $TEST_OPTIONS

Examples tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cd test
    - ./checks_examples.sh $TEST_OPTIONS

Utils tests:
  stage: checks
  image: lesurg/idefix:latest
  script:
    - cd test
    - ./checks_utils.sh $TEST_OPTIONS

pages:
  image: lesurg/idefix-documentation:latest
  stage: deploy
  script:
    - dir="public"
    - rm -rf $dir
    - sphinx-build -b html doc/source $dir
  artifacts:
    paths:
      - public
  only:
  - master
