workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'      # Execute jobs when a new commit is pushed to master branch

test:
  image: ubuntu:latest

  variables:
    OMPI_ALLOW_RUN_AS_ROOT: '1'
    OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: '1'
    OMPI_MCA_btl_vader_single_copy_mechanism: 'none' # https://github.com/open-mpi/ompi/issues/4948

  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qq
    - apt-get install -qq build-essential openmpi-bin python3 python3-pip bc git
  stage: test
  script:
    - cat /proc/cpuinfo
    - gcc --version

    # todo: move these to requirements_tests.txt
    # pip3
    - pip3 install numpy
    - pip3 install scipy
    - pip3 install matplotlib
    - pip3 install pre-commit && pre-commit install

    - git submodule init
    - git submodule update

    # linting (this should go to a separate stage/task)
    - cd test/style
    - pre-commit run --all-files > code_quality.txt
    - ./check_idefix_style.sh >> code_quality.txt

    # actual CI
    - cd ..
    - ./checks.sh
    - ./checks_mpi.sh
  artifacts:
    reports:
      codequality: test/style/code_quality.txt
  # only:
  #- schedules
  #except:
  #- master

pages:
  image: python:3.7-alpine
  stage: deploy
  script:
  - pip install -U sphinx sphinx-rtd-theme
  - sphinx-build -b html doc/source public
  artifacts:
    paths:
    - public
  only:
  - master
