exclude: "^(src/kokkos)"

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace  # auto-fix trailing whitespaces
      - id: end-of-file-fixer  # add EOF "\n" if missing
      - id: no-commit-to-branch  # forbid direct commits to master
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: markdown-toc
        files: README.md

  - repo: https://github.com/neutrinoceros/inifix
    rev: v2.0.0
    hooks:
      - id: inifix-format

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.12
    hooks:
      - id: remove-tabs  # auto-fix tab/space mixing
      - id: insert-license
        files: ^(src/).*\.(hpp|cpp)$
        args:
        - --license-filepath
        - src/license_header.txt
        - --comment-style
        - //

  - repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0
    hooks:
      - id: cpplint
        args: [--counting=detailed, --exclude=test/*]
