exclude: "^(src/kokkos)"

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace  # auto-fix trailing whitespaces
      - id: end-of-file-fixer  # add EOF "\n" if missing
      - id: no-commit-to-branch  # forbid direct commits to master
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-executables-have-shebangs

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: markdown-toc
        files: README.md

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: remove-tabs  # auto-fix tab/space mixing
      - id: insert-license
        files: ^(src/).*\.(hpp|cpp)$
        args:
        - --license-filepath
        - src/license_header.txt
        - --comment-style
        - //

  - repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0
    hooks:
      - id: cpplint
        args: [--counting=detailed, --exclude=test/*]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma
        files: "configure.py"

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
    - id: flake8
      additional_dependencies: [
        flake8-bugbear,
      ]
      files: "configure.py"
      args: ["--ignore", "E501"]
