name: Idefix CIs
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - test-ci
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*'

jobs:
  icc-jobs:
    name: CPU Jobs (icc)
    uses: ./.github/workflows/idefix-ci-jobs.yml
    with:
      TESTME_OPTIONS: -Werror
      IDEFIX_COMPILER: icc

  gcc-jobs:
    name: CPU Jobs (gcc)
    uses: ./.github/workflows/idefix-ci-jobs.yml
    with:
      TESTME_OPTIONS: -Werror
      IDEFIX_COMPILER: gcc

  cuda-jobs:
    name: CUDA Jobs
    uses: ./.github/workflows/idefix-ci-jobs.yml
    with:
      TESTME_OPTIONS: -cuda -Werror
      IDEFIX_COMPILER: cuda
